# Generated by Django 4.2.3 on 2023-07-12 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("slug", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("material", models.CharField(max_length=100)),
                ("dimensions", models.CharField(max_length=100)),
                ("installation_process", models.TextField()),
                ("additional_benefits", models.TextField()),
                ("image", models.ImageField(blank=True, upload_to="product/")),
            ],
        ),
    ]
