# Generated by Django 4.2.3 on 2023-07-21 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0002_product_short_desc"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="video_url",
            field=models.TextField(blank=True),
        ),
    ]
